CREATE TABLE DIRECCION(
             ID_DIRECCION INTEGER,
             CALLE VARCHAR(120),
             COLONIA VARCHAR(120),
             ESTADO VARCHAR(120),
             CONSTRAINT ID_DIRECCION PRIMARY KEY(ID_DIRECCION)

);
