CREATE TABLE USUARIO(
             ID_USUARIO INTEGER,
             NOMBRE VARCHAR(120),
             EDAD VARCHAR(120),
             SALDO FLOAT,
           CONSTRAINT ID_USUARIO PRIMARY KEY (ID_USUARIO),
           CONSTRAINT ID_DIRECCION USUARIO FOREIGN KEY(ID_DIRECCION)REFERENCES DIRECCION(ID_DIRECCION)

);
